### ISSUE TITLE
Update Video on landing page to summit video

### ISSUE THREAD

**Issue by MichaelClifford** [operate-first/operate-first-in-action#12]

**Comment by MichaelClifford** [comment]
Need to get details from Summit team on when we can publicly publish the video.

**Comment by MichaelClifford** [comment]
This has been done! Thanks @schwesig 

Video can be found at https://youtu.be/sfjAr5EI2ww and will go live the morning of May 10th, 2022 at the start of summit

**Comment by schwesig** [comment]
https://github.com/operate-first/operate-first-in-action/pull/17

**Comment by schwesig** [comment]
https://github.com/operate-first/operate-first-in-action/pull/16
