### ISSUE TITLE
Upload to Youtube

### ISSUE THREAD

**Issue by MichaelClifford** [operate-first/operate-first-in-action#15]

**Comment by schwesig** [comment]
https://youtu.be/sfjAr5EI2ww
premiere on May, 10th 2022
10am ET
I will add it on the page via PR https://github.com/operate-first/operate-first-in-action/pull/16

**Comment by schwesig** [comment]
can the "youtube magicians" check, if I should

- [ ] add some more tags, banners etc?
- [ ] change the premiere time (sync with the time schedule of RH Summit)? 
- [ ] add some more description, links, name change, playlist naming?
- [ ] change/rename the playlist

@MichaelClifford @durandom
