### ISSUE TITLE
Create a redirect entry to long running meteor book!

### ISSUE THREAD

**Issue by MichaelClifford** [operate-first/operate-first-in-action#5]
- [ ] google analytics is tracked!

**Comment by aakankshaduggal** [comment]
Due to https://github.com/operate-first/support/issues/554, meteor is unavailable atm. Hence, we are not able to create a meteor book for this repo.

**Comment by aakankshaduggal** [comment]
Long-running Meteor Book is now available - http://operate-first-in-action.catalog.meteor.zone/

**Comment by MichaelClifford** [comment]
@aakankshaduggal what is the process for updating that jupyterbook? We are getting close to having our final version of content ready.

**Comment by MichaelClifford** [comment]
@aakankshaduggal What needs to happen to get operate-first.cloud/action to redirect to our jupyterbook?

**Comment by aakankshaduggal** [comment]
Added GA id to the meteor book.
